/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#002113",
        "on-tertiary": "#003824",
        "inverse-on-surface": "#2d3038",
        "surface-container-highest": "#32353d",
        "surface-dim": "#10131a",
        "on-primary-fixed": "#07006c",
        "error-container": "#93000a",
        "on-surface-variant": "#c7c4d7",
        "tertiary-container": "#00885d",
        "surface-tint": "#c0c1ff",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed-dim": "#7bd0ff",
        "secondary-container": "#00a6e0",
        "on-secondary-fixed": "#001e2c",
        "tertiary": "#4edea3",
        "on-primary": "#1000a9",
        "outline": "#908fa0",
        "primary-fixed": "#e1e0ff",
        "surface": "#10131a",
        "primary-fixed-dim": "#c0c1ff",
        "secondary-fixed": "#c4e7ff",
        "on-primary-fixed-variant": "#2f2ebe",
        "error": "#ffb4ab",
        "surface-container-high": "#272a32",
        "on-secondary-container": "#00374d",
        "on-primary-container": "#0d0096",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e1e2ec",
        "secondary": "#7bd0ff",
        "on-secondary": "#00354a",
        "surface-container-low": "#191b23",
        "on-surface": "#e1e2ec",
        "on-error": "#690005",
        "surface-container": "#1d1f27",
        "inverse-primary": "#494bd6",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary-container": "#000703",
        "outline-variant": "#464554",
        "surface-bright": "#363941",
        "primary-container": "#8083ff",
        "background": "#10131a",
        "primary": "#c0c1ff",
        "surface-container-lowest": "#0b0e15",
        "on-secondary-fixed-variant": "#004c69",
        "on-background": "#e1e2ec",
        "surface-variant": "#32353d",
        "on-tertiary-fixed-variant": "#005236",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        "3xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        margin: "1rem",
        "margin-desktop": "2rem",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "metric-val": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "metric-val": ["14px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "500" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.005em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
